#!/usr/bin/env bash

set -exo pipefail

BLOOP_REV_TO_FIND='1.3.2+278-549e1f8c+20190917-1756'

java_opts=()
server_args=()
for arg in "$@"; do
  if [[ $arg == -J* ]]; then
    # java_opts+=(${arg#"-J"})
    java_opts+=($arg)
  else
    server_args+=($arg)
  fi
done

echo "Detected java options are '${java_opts[@]}'"
BASE_BIN_DIR=$(dirname "$0")
COURSIER_BIN="$BASE_BIN_DIR/blp-coursier"

function merge_jars {
  tr '\n' ':' | sed -Ee 's#:$##g' \
    && echo
}

export JAVA_HOME="/Users/dmcclanahan/Downloads/openjdk1.8.0_202-jvmci-0.59/Contents/Home"
PATH="${JAVA_HOME}/bin:${PATH}"

function run_with_java_home {
  /usr/libexec/java_home \
    -v 1.8 -F -R --exec java \
    "$@"
}

# function scala_packaged_jars {
#   printf "%s\n" ~/tools/scala/build/pack/lib/*.jar
# }

function rsc_packaged_jars {
  coursier fetch 'com.twitter:rsc_2.12:0.0.0-852-4e537fc2-20190917-1526'
}

run_with_java_home -jar "$COURSIER_BIN" \
                   fetch \
                   "ch.epfl.scala:bloop-frontend_2.12:${BLOOP_REV_TO_FIND}" \
  | merge_jars | while read -r merged_bloop_cp; do

  # NB: see https://docs.oracle.com/javase/7/docs/technotes/samples/hprof.html for hprof options.
  ~/tools/scala/build/pack/bin/scala \
    -J-Xmx9g -J-Xms2g \
    "${java_opts[@]}" \
    -J-agentlib:hprof=cpu=samples,interval=5,depth=100,thread=y \
    -cp "$merged_bloop_cp" \
    bloop.Server \
    "${server_args[@]}"
done
